id = "zed oled"
name = "Zed OLED"
version = "0.1.0"
schema_version = 1
authors = ["Davi Aragorn <daviaragorn@gmail.com>"]
description = "A Zed theme with pure blacks"
repository = "https://github.com/DaviAragorn/OLED-Zed"
